### ISSUE TITLE
No such file or directory checkpoint_map.json when restoring model from model selection

### ISSUE THREAD

**Issue by galeone** [zurutech/ashpy#37]
The title says pretty much everything.

Creating a restorer (in particular a ClassifierRestorer but it is not important) passing as checkpoint directory, the directory where the checkpoint of the best model has been saved causes an error.

two options:

1. We have to create the same file also when doing model selection
2. We have to make it possible to restore the model from the checkpoint even if the file is not present

I like the first one

**Comment by EmanueleGhelfi** [comment]
Just to mention another possibility we have. We can design a restorer that takes as input a metric (or its name) and restores the best model for the metric passed. In this way the user can ignore the logdir structure and restore directly the best model for a given metric passing just the logdir name (and not the directory of the best model for a given metric).

**Comment by mr-ubik** [comment]
We should do both, if the "checkpoint_map" is not found we should not throw an exception but maybe raise a warning.
