### ISSUE TITLE
Setup Travis

### ISSUE THREAD

**Issue by EmanueleGhelfi** [zurutech/ashpy#6]
I think we can setup Travis in order to automate tests and deployment. Travis can be used to automatic deployment on pypi in this way: https://docs.travis-ci.com/user/deployment/pypi/.

**Comment by EmanueleGhelfi** [comment]
More on this: If we want to deploy branches starting with "release" for example https://docs.travis-ci.com/user/customizing-the-build/#using-regular-expressions

**Comment by galeone** [comment]
:+1: for TravisCI. Setting it up to start and check if a PR passes all the tests is a must-have.
